In [1]:
import pandas as pd
df = pd.read_parquet( "data/data.parquet" )
df.describe()

,date,price,beta_1y,alpha_1y,log_market_cap,pe,future_5y_return,ret_1d,ret_1w,ret_1m,...,excess_ret_5y,trend_vs_sector_1y,trend_vs_sector_5y,drawdown_rel_1y,drawdown_rel_5y,excess_vs_market_1y,trend_vs_market_1y,risk_adjusted_1y,risk_adjusted_5y,quality_score
count,926481,9.264810e+05,926481.000000,9.264810e+05,902678.000000,6.251770e+05,926481.000000,926481.000000,926481.000000,926481.000000,...,9.264810e+05,9.264810e+05,9.264810e+05,9.264810e+05,9.264810e+05,9.264810e+05,9.264810e+05,9.264810e+05,9.264810e+05,926481.000000
mean,2019-01-01 16:06:02.952000,7.011126e+11,0.965376,-2.283982e-04,20.715494,6.944339e+06,19.939266,0.019239,0.152302,0.487435,...,2.674548e-15,-4.673458e-21,9.286999e-22,4.754944e-19,1.748592e-18,-1.325249e-17,-5.212703e-21,1.641222e-18,7.976035e-19,1.427510
min,2016-06-29 00:00:00,1.000000e-05,-3.313673,-1.350363e+03,6.807943,6.996410e-05,-6224.654933,-0.999733,-0.999733,-0.999850,...,-6.389863e+03,-1.209684e-01,-3.079803e-02,-9.049383e-01,-8.585398e-01,-5.562599e+01,-1.216269e-01,-4.533019e+00,-2.574695e+00,0.000000
25%,2017-09-28 00:00:00,5.674606e+00,-0.000042,-8.806071e-03,18.936030,5.052705e+00,-0.248736,-0.008113,-0.021276,-0.044747,...,-1.276324e+00,-7.725569e-04,-2.055019e-04,-8.377614e-02,-1.850771e-01,-1.139950e+00,-8.073552e-04,-2.024721e-01,-2.787189e-01,0.000000
50%,2018-12-31 00:00:00,1.664702e+01,0.007926,6.436107e-08,20.786008,9.180297e+00,0.251773,0.000000,0.000000,0.005640,...,-5.269955e-01,9.530536e-05,1.598247e-04,5.813751e-02,7.594250e-02,-5.744635e-01,1.248563e-04,-8.255440e-02,-1.024998e-01,1.000000
75%,2020-04-01 00:00:00,4.415855e+01,0.043142,8.698310e-03,22.574356,1.827440e+01,0.920505,0.009091,0.024772,0.062464,...,1.103069e-01,8.932163e-04,5.462723e-04,1.315472e-01,1.982848e-01,-2.409303e-01,9.195992e-04,9.572645e-03,3.626485e-02,2.000000
max,2021-07-01 00:00:00,7.627500e+15,3684.900604,1.526700e+03,49.705002,1.699894e+11,579999.033726,5999.000390,105051.500603,111254.600638,...,1.092110e+06,4.868898e-02,9.636796e-03,6.733719e-01,6.936064e-01,1.999444e+05,4.843067e-02,2.992174e+01,2.991213e+01,3.000000
std,NaN,4.786128e+13,49.055828,2.857776e+00,2.773924,7.582107e+08,2208.695822,7.711553,109.519297,182.611992,...,3.548276e+03,2.776540e-03,1.294761e-03,2.073956e-01,2.865172e-01,4.386627e+02,2.825389e-03,9.983607e-01,9.983607e-01,1.089255

In [2]:
# Cell 1
import pandas as pd
import numpy as np
df = pd.read_parquet("data/data.parquet")

# Cell 2 — run this, look at output, then edit and re-run without re-loading data
df["future_5y_return"].describe(percentiles=[.01, .05, .5, .95, .99, .999])

# Cell 3
df.nlargest(10, "future_5y_return")[["ticker", "date", "price", "future_5y_return"]]

       ticker       date    price  future_5y_return
480151   NXMH 2016-08-18  0.00001     579999.033726
480145   NXMH 2016-07-07  0.00001     546998.992838
480146   NXMH 2016-07-14  0.00001     539999.023178
480147   NXMH 2016-07-21  0.00001     469998.992800
480152   NXMH 2016-08-25  0.00001     451999.009511
480144   NXMH 2016-06-29  0.00001     449999.011368
480153   NXMH 2016-09-01  0.00001     448998.988455
480149   NXMH 2016-08-04  0.00001     429999.029936
480148   NXMH 2016-07-28  0.00001     419499.027764
480150   NXMH 2016-08-11  0.00001     408999.025591

In [3]:
# Find Outliers

df = pd.read_parquet("data/data.parquet")
print(df["future_5y_return"].describe(percentiles=[.01, .05, .5, .95, .99, .999]))
print(df.nlargest(10, "future_5y_return")[["ticker", "date", "price", "future_5y_return"]])

count    926481.000000
mean         19.939266
std        2208.695822
min       -6224.654933
1%           -0.997807
5%           -0.918794
50%           0.251773
95%           3.618920
99%          15.000000
99.9%       369.000009
max      579999.033726
Name: future_5y_return, dtype: float64
       ticker       date    price  future_5y_return
480151   NXMH 2016-08-18  0.00001     579999.033726
480145   NXMH 2016-07-07  0.00001     546998.992838
480146   NXMH 2016-07-14  0.00001     539999.023178
480147   NXMH 2016-07-21  0.00001     469998.992800
480152   NXMH 2016-08-25  0.00001     451999.009511
480144   NXMH 2016-06-29  0.00001     449999.011368
480153   NXMH 2016-09-01  0.00001     448998.988455
480149   NXMH 2016-08-04  0.00001     429999.029936
480148   NXMH 2016-07-28  0.00001     419499.027764
480150   NXMH 2016-08-11  0.00001     408999.025591