In [8]:
import pandas as pd
df = pd.read_parquet( "data/data.parquet" )
df.describe()

,date,price,beta_1y,alpha_1y,log_market_cap,pe,future_5y_return,ret_1d,ret_1w,ret_1m,...,excess_ret_5y,trend_vs_sector_1y,trend_vs_sector_5y,drawdown_rel_1y,drawdown_rel_5y,excess_vs_market_1y,trend_vs_market_1y,risk_adjusted_1y,risk_adjusted_5y,quality_score
count,891505,8.915050e+05,891505.000000,8.915050e+05,867750.000000,6.221760e+05,891505.000000,891505.000000,891505.000000,891505.000000,...,8.915050e+05,8.915050e+05,8.915050e+05,8.915050e+05,8.915050e+05,8.915050e+05,8.915050e+05,8.915050e+05,8.915050e+05,891505.000000
mean,2019-01-01 04:42:19.926000,7.286190e+11,0.642785,2.619117e-03,20.939611,6.977835e+06,0.683251,0.019082,0.152701,0.493951,...,1.069148e-15,1.291164e-18,1.785313e-18,-3.028656e-19,5.419701e-19,3.591030e-16,-2.167880e-18,-7.173134e-19,2.869254e-19,1.393429
min,2016-06-29 00:00:00,1.000000e-01,-2.322781,-7.549203e+02,12.183012,2.818981e-02,-4.698661,-0.950000,-0.999500,-0.999625,...,-6.427139e+03,-1.221512e+01,-1.209731e+01,-9.162045e-01,-8.728477e-01,-5.811675e+01,-1.217846e+01,-4.637479e+00,-2.670781e+00,0.000000
25%,2017-09-28 00:00:00,6.675951e+00,-0.000018,-8.978227e-03,19.139602,5.102946e+00,-0.241913,-0.008333,-0.021099,-0.043263,...,-1.134924e+00,-2.114525e-01,-6.288060e-01,-7.761379e-02,-1.678861e-01,-1.027841e+00,-2.181629e-01,-2.341742e-01,-3.171909e-01,1.000000
50%,2018-12-31 00:00:00,1.790450e+01,0.008391,7.474730e-08,20.928234,9.231411e+00,0.246479,0.000000,0.000000,0.007043,...,-4.637109e-01,-1.853349e-02,-1.652444e-01,5.236634e-02,7.161279e-02,-4.854480e-01,-2.474528e-02,-8.252430e-02,-1.074668e-01,1.000000
75%,2020-04-01 00:00:00,4.612945e+01,0.043404,8.916032e-03,22.649592,1.835357e+01,0.882192,0.009354,0.024953,0.062246,...,1.547185e-01,1.893359e-01,2.663956e-01,1.225947e-01,1.881424e-01,-1.758716e-01,1.980574e-01,3.717544e-02,6.254004e-02,2.000000
max,2021-07-01 00:00:00,7.627500e+15,3684.900604,1.526700e+03,49.705002,1.699894e+11,918.593314,5999.000390,105051.500603,111254.600638,...,1.092073e+06,1.555037e+01,2.890393e+01,6.758775e-01,6.877736e-01,1.999419e+05,1.565515e+01,2.955737e+01,2.961417e+01,3.000000
std,NaN,4.879090e+13,38.931367,2.436195e+00,2.550789,7.600369e+08,3.779321,7.858610,111.623780,186.142436,...,3.616992e+03,6.263213e-01,1.455755e+00,1.943800e-01,2.744517e-01,4.469403e+02,6.391575e-01,9.982964e-01,9.982964e-01,0.600336

In [9]:
# Cell 1
import pandas as pd
import numpy as np
df = pd.read_parquet("data/data.parquet")

# Cell 2 — run this, look at output, then edit and re-run without re-loading data
df["future_5y_return"].describe(percentiles=[.01, .05, .5, .95, .99, .999])

# Cell 3
df.nlargest(10, "future_5y_return")[["ticker", "date", "price", "future_5y_return"]]

       ticker       date     price  future_5y_return
238300   CHRD 2020-10-06  0.104255        918.593314
238274   CHRD 2020-04-01  0.177848        590.649789
238276   CHRD 2020-04-16  0.165582        507.130292
238272   CHRD 2020-03-18  0.214644        465.004794
238273   CHRD 2020-03-25  0.226909        454.341777
238275   CHRD 2020-04-08  0.196246        420.440669
238271   CHRD 2020-03-11  0.239174        401.951980
238299   CHRD 2020-09-29  0.251440        401.065455
238298   CHRD 2020-09-22  0.251440        385.064392
238280   CHRD 2020-05-14  0.245307        373.814443

In [10]:
# Find Outliers

df = pd.read_parquet("data/data.parquet")
print(df["future_5y_return"].describe(percentiles=[.01, .05, .5, .95, .99, .999]))
print(df.nlargest(10, "future_5y_return")[["ticker", "date", "price", "future_5y_return"]])

count    891505.000000
mean          0.683251
std           3.779321
min          -4.698661
1%           -0.997821
5%           -0.915216
50%           0.246479
95%           3.134752
99%           8.275000
99.9%        31.500002
max         918.593314
Name: future_5y_return, dtype: float64
       ticker       date     price  future_5y_return
238300   CHRD 2020-10-06  0.104255        918.593314
238274   CHRD 2020-04-01  0.177848        590.649789
238276   CHRD 2020-04-16  0.165582        507.130292
238272   CHRD 2020-03-18  0.214644        465.004794
238273   CHRD 2020-03-25  0.226909        454.341777
238275   CHRD 2020-04-08  0.196246        420.440669
238271   CHRD 2020-03-11  0.239174        401.951980
238299   CHRD 2020-09-29  0.251440        401.065455
238298   CHRD 2020-09-22  0.251440        385.064392
238280   CHRD 2020-05-14  0.245307        373.814443

In [12]:
import pandas as pd
df = pd.read_parquet("data/raw_data.parquet")
print(f"Columns (tickers): {len(df.columns)}")

Columns (tickers): 3685